### PR TITLE
Refactor into Python package

### PR DESCRIPTION
**Pull request by sdahdah**
Hi,

I refactored your code (thanks very much for writing it) into a package that can be put onto PyPI. It can now be installed with `pip install ./optht` once cloned.

I also renamed a couple functions and added some docstrings. If you're not ok with those changes, I can revert them. The most important part for me is the folder structure.

If you're ok with this, could we consider submitting it to PyPI for easy installation?

### CODE REVIEW

**Comment by erichson** [comment]
@sdahdah that is really amazing! Thank you for putting time and effort into this! I am happy to submit it to PyPI.

**Comment by sdahdah** [comment]
Glad you found it handy. If you need any help with PyPI just let me know!

**Comment by sdahdah** [comment]
By the way, I didn't mean to add my name into the readme and merge into your repo... I added that line before I was planning to PR the fork, then I forgot it was there. You can remove that line if you want.

**Comment by erichson** [comment]
@sdahdah I updated the readme and acknowledged you. Are you happy with it as it is, otherwise feel free to change it. Also I am happy to add you as an author to the setup.py? You made some considerable changes.

**Comment by sdahdah** [comment]
Well I don't really need to be acknowledged twice in the same file :P You can remove that bullet from the notes section (I won't fork and make a PR just for that).

If you wanna add me in the setup.py, go for it, I'd be honoured! My email is firstname.lastname@mail.mcgill.ca

I'm happy to help maintain this package if people submit issues and stuff. I'm using it for my research, so if I write any enhancements I'll create an issue and we can chat about it.

**Comment by erichson** [comment]
You are added as an author. Have a look at https://pypi.org/project/optht/0.2.0/.

Btw. have a look at this paper: https://arxiv.org/pdf/2009.12297.pdf. They have a python package, but maybe it is a nice extension to include it also into the optht package.

Best,
Ben

**Pull request merged**
